[project]
name = "tts-keyboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "piper-tts>=1.3.0",
    "PyAudio>=0.2.0",
]
